Fix transformer.ipynb
In the latest version of tensorflow, this example fails, because vocab_size is a scalar tensor (type EagerTensor) and keras can't determine the dtype.  The failure occurs pretty deep in the call stack, so it's best to determine as early as possible whether that type conversion is going to succeed or not.

Python3.10
TensorFlow 2.16.1

Attached is the relevant part of the traceback:
  File "/home/olivas/qaintum.ai/./transformer.py", line 404, in call
    x = self.embedding(x)
  File "/home/olivas/qaintum.ai/venv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 113, in error_handler
    return fn(*args, **kwargs)
  File "/home/olivas/qaintum.ai/venv/lib/python3.10/site-packages/keras/src/layers/layer.py", line 771, in __call__
    self._maybe_build(call_spec)
  File "/home/olivas/qaintum.ai/venv/lib/python3.10/site-packages/keras/src/layers/layer.py", line 1279, in _maybe_build
    self.build(**shapes_dict)
  File "/home/olivas/qaintum.ai/venv/lib/python3.10/site-packages/keras/src/layers/layer.py", line 223, in build_wrapper
    original_build_method(*args, **kwargs)
  File "/home/olivas/qaintum.ai/venv/lib/python3.10/site-packages/keras/src/layers/core/embedding.py", line 124, in build
    self._embeddings = self.add_weight(
  File "/home/olivas/qaintum.ai/venv/lib/python3.10/site-packages/keras/src/layers/layer.py", line 511, in add_weight
    variable = backend.Variable(
  File "/home/olivas/qaintum.ai/venv/lib/python3.10/site-packages/keras/src/backend/common/variables.py", line 161, in __init__
    shape = self._validate_shape(shape)
  File "/home/olivas/qaintum.ai/venv/lib/python3.10/site-packages/keras/src/backend/common/variables.py", line 184, in _validate_shape
    shape = standardize_shape(shape)
  File "/home/olivas/qaintum.ai/venv/lib/python3.10/site-packages/keras/src/backend/common/variables.py", line 549, in standardize_shape
    if not is_int_dtype(type(e)):
  File "/home/olivas/qaintum.ai/venv/lib/python3.10/site-packages/keras/src/backend/common/variables.py", line 580, in is_int_dtype
    dtype = standardize_dtype(dtype)
  File "/home/olivas/qaintum.ai/venv/lib/python3.10/site-packages/keras/src/backend/common/variables.py", line 521, in standardize_dtype
    raise ValueError(f"Invalid dtype: {dtype}")
ValueError: Invalid dtype: <property object at 0x7f6c0c458d10>
Exception ignored in: <function AtomicFunction.__del__ at 0x7f6c0b4dbc70>